### ISSUE TITLE
How to login firsttime?

### ISSUE THREAD

**Issue by MalkusCZ** [ipmanlk/EasySystem#2]
After download system there are no possibly to login, there are only one your user, but is not able to recognize password, or ability to create a newone.

**Comment by ipmanlk** [comment]
> After download system there are no possibly to login, there are only one your user, but is not able to recognize password, or ability to create a newone.

@MalkusCZ - Sorry about that. Use **sha123** as the password. I will release an installation script for this soon. Until then, you can manually edit username & password by using phpmyadmin.
